include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    sort_child_properties_last: true
    avoid_print: true
    prefer_final_in_for_each: true
    prefer_double_quotes: true
    unnecessary_parenthesis: false
    prefer_foreach: true
    prefer_relative_imports: false
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true
    empty_constructor_bodies: false
    unnecessary_string_interpolations: false
    unnecessary_await_in_return: false
    unnecessary_final: false
    unnecessary_null_checks: false
    avoid_unused_constructor_parameters: true
    avoid_unnecessary_containers: true   
    sort_unnamed_constructors_first: true  
    secure_pubspec_urls: true
    always_use_package_imports: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: false
    list_remove_unrelated_type: true
    iterable_contains_unrelated_type: true
    no_duplicate_case_values: true
    unnecessary_statements: false
    missing_whitespace_between_adjacent_strings: false
    no_default_cases: true
    no_runtimeType_toString: true
    prefer_iterable_whereType: true
    sized_box_shrink_expand: true
    super_goes_last: true
    unnecessary_overrides: false
    use_key_in_widget_constructors: true